import { Report } from '../types';
import { CATEGORIES, HAZARD_LEVELS } from '../constants/categories';
import { supabase } from './supabase';
import { Share } from 'react-native';

// ============================================================
// Insurance Claim Evidence Packager
// Bundles timestamped GPS evidence, photos, report history,
// escalation log, and authority notification proof into
// a shareable evidence package for insurance claims.
// ============================================================

export interface ClaimEvidence {
  summary: string;
  reportId: string;
  category: string;
  location: {
    address: string;
    gps: string;
    mapsUrl: string;
  };
  timeline: TimelineEvent[];
  authorityNotification: {
    wasNotified: boolean;
    notifiedDate?: string;
    authorityName?: string;
    daysSinceNotification?: number;
    method?: string;
  };
  communityVerification: {
    totalReports: number;
    uniqueReporters: number;
    confirmations: number;
  };
  severity: {
    hazardLevel: string;
    sizeRating?: string;
  };
  mediaUrls: string[];
  generatedAt: string;
  fullText: string;
}

interface TimelineEvent {
  date: string;
  event: string;
  detail?: string;
}

export async function generateClaimEvidence(
  report: Report,
  vehicleDamageDescription?: string,
  damageDate?: string,
  estimatedCost?: number,
): Promise<ClaimEvidence> {
  const category = CATEGORIES.find((c) => c.key === report.category);
  const hazard = HAZARD_LEVELS.find((h) => h.key === report.severity.hazardLevel);
  const location = report.location;
  const locationStr = [location.address, location.city, location.state].filter(Boolean).join(', ');

  // Build timeline
  const timeline: TimelineEvent[] = [];

  timeline.push({
    date: new Date(report.createdAt).toLocaleDateString(),
    event: 'Hazard first reported',
    detail: `${category?.label} reported at ${locationStr} via Fault Line`,
  });

  // Get cluster data for community verification
  let totalReports = 1;
  let uniqueReporters = 1;
  if (report.clusterId) {
    const { data: cluster } = await supabase
      .from('report_clusters')
      .select('report_count, unique_reporters, first_reported_at, status, submitted_at')
      .eq('id', report.clusterId)
      .single();

    if (cluster) {
      totalReports = cluster.report_count;
      uniqueReporters = cluster.unique_reporters;

      if (cluster.unique_reporters >= 3) {
        timeline.push({
          date: new Date(cluster.first_reported_at).toLocaleDateString(),
          event: 'Community verified',
          detail: `${cluster.unique_reporters} independent reporters confirmed the hazard`,
        });
      }

      if (cluster.submitted_at) {
        timeline.push({
          date: new Date(cluster.submitted_at).toLocaleDateString(),
          event: 'Authority formally notified',
          detail: 'Professional report sent to responsible authority',
        });
      }
    }
  }

  // Get escalation log
  let authorityNotification = { wasNotified: false } as ClaimEvidence['authorityNotification'];
  if (report.clusterId) {
    const { data: escalations } = await supabase
      .from('escalation_log')
      .select('*')
      .eq('cluster_id', report.clusterId)
      .eq('status', 'sent')
      .order('sent_at', { ascending: true })
      .limit(1);

    if (escalations && escalations.length > 0) {
      const esc = escalations[0];
      const sentDate = new Date(esc.sent_at);
      authorityNotification = {
        wasNotified: true,
        notifiedDate: sentDate.toLocaleDateString(),
        authorityName: esc.recipient,
        daysSinceNotification: Math.floor((Date.now() - sentDate.getTime()) / 86400000),
        method: esc.method,
      };

      timeline.push({
        date: sentDate.toLocaleDateString(),
        event: `Authority contacted via ${esc.method}`,
        detail: `Sent to: ${esc.recipient}`,
      });
    }
  }

  if (damageDate) {
    timeline.push({
      date: damageDate,
      event: 'Vehicle damage occurred',
      detail: vehicleDamageDescription || 'Damage sustained from reported hazard',
    });
  }

  timeline.push({
    date: new Date().toLocaleDateString(),
    event: 'Evidence package generated',
    detail: 'Claim evidence compiled from community reporting platform',
  });

  // Sort timeline chronologically
  timeline.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

  const mediaUrls = report.media
    .map((m) => m.uploadedUrl)
    .filter((url): url is string => !!url);

  const daysSinceReport = Math.floor((Date.now() - new Date(report.createdAt).getTime()) / 86400000);

  // Generate full text report
  const fullText = `
INSURANCE CLAIM EVIDENCE PACKAGE
Generated by Fault Line — Community Infrastructure Accountability Platform
${'═'.repeat(60)}

Date Generated: ${new Date().toLocaleDateString()}
Report ID: ${report.id}
${report.clusterId ? `Cluster ID: ${report.clusterId}` : ''}

HAZARD INFORMATION
${'─'.repeat(60)}
Type: ${category?.label || report.category}
Location: ${locationStr}
GPS Coordinates: ${location.latitude.toFixed(6)}, ${location.longitude.toFixed(6)}
Google Maps: https://maps.google.com/?q=${location.latitude},${location.longitude}
Hazard Level: ${hazard?.label || report.severity.hazardLevel}
${report.severity.sizeRating ? `Size: ${report.severity.sizeRating}` : ''}
${report.description ? `Description: ${report.description}` : ''}

COMMUNITY VERIFICATION
${'─'.repeat(60)}
Total Independent Reports: ${totalReports}
Unique Reporters: ${uniqueReporters}
Community Confirmations: ${report.confirmCount}
Days Hazard Has Been Reported: ${daysSinceReport}

AUTHORITY NOTIFICATION STATUS
${'─'.repeat(60)}
${authorityNotification.wasNotified
  ? `Authority Was Notified: YES
Notification Date: ${authorityNotification.notifiedDate}
Authority: ${authorityNotification.authorityName}
Method: ${authorityNotification.method}
Days Since Notification: ${authorityNotification.daysSinceNotification}
Status: ${report.status === 'resolved' ? 'RESOLVED' : 'UNRESOLVED — Authority failed to remedy the condition'}`
  : 'Authority notification status: Pending community verification threshold'}

${vehicleDamageDescription ? `DAMAGE DESCRIPTION
${'─'.repeat(60)}
Date of Damage: ${damageDate || 'Not specified'}
Description: ${vehicleDamageDescription}
${estimatedCost ? `Estimated Cost: $${estimatedCost.toLocaleString()}` : ''}
` : ''}

TIMELINE OF EVENTS
${'─'.repeat(60)}
${timeline.map((e) => `${e.date}  |  ${e.event}${e.detail ? `\n${' '.repeat(14)}${e.detail}` : ''}`).join('\n')}

PHOTOGRAPHIC EVIDENCE
${'─'.repeat(60)}
${mediaUrls.length > 0
  ? mediaUrls.map((url, i) => `Photo ${i + 1}: ${url}`).join('\n')
  : 'No photos uploaded (community severity assessments available)'}

LEGAL NOTE
${'─'.repeat(60)}
This evidence package was automatically generated from data collected by the Fault Line community infrastructure reporting platform. All reports were independently submitted by community members with GPS-verified locations and timestamps. This data may be used to support insurance claims, municipal liability claims, or Freedom of Information Act requests.

${'═'.repeat(60)}
Fault Line — Because your tax dollars should fix this faster.
`.trim();

  return {
    summary: `${category?.label} at ${locationStr} — ${daysSinceReport} days unresolved, ${totalReports} reports`,
    reportId: report.id,
    category: category?.label || report.category,
    location: {
      address: locationStr,
      gps: `${location.latitude.toFixed(6)}, ${location.longitude.toFixed(6)}`,
      mapsUrl: `https://maps.google.com/?q=${location.latitude},${location.longitude}`,
    },
    timeline,
    authorityNotification,
    communityVerification: {
      totalReports,
      uniqueReporters,
      confirmations: report.confirmCount,
    },
    severity: {
      hazardLevel: hazard?.label || report.severity.hazardLevel,
      sizeRating: report.severity.sizeRating,
    },
    mediaUrls,
    generatedAt: new Date().toISOString(),
    fullText,
  };
}

export async function shareClaimEvidence(evidence: ClaimEvidence): Promise<void> {
  await Share.share({
    message: evidence.fullText,
    title: `Insurance Claim Evidence — ${evidence.category} at ${evidence.location.address}`,
  });
}
