import { supabase } from './supabase';
import { estimateRepairCost } from './costEstimation';

// ============================================================
// Seasonal Pre-Deployment Reports
// Predict where damage will occur before the season hits.
// Generate proactive maintenance reports for cities.
// ============================================================

export interface SeasonalPrediction {
  location: { lat: number; lng: number; address?: string; city?: string };
  category: string;
  historicalReports: number;
  yearsRecurring: number;
  typicalMonths: string[]; // e.g., ["March", "April"]
  estimatedRepairCost: number;
  confidence: number;
  recommendation: string;
}

export interface PreDeploymentReport {
  title: string;
  city: string;
  state: string;
  season: string;
  generatedAt: string;
  predictions: SeasonalPrediction[];
  totalEstimatedCost: number;
  proactiveSavings: number; // Estimated savings vs reactive repair
  fullText: string;
}

const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

export async function generatePreDeploymentReport(
  city: string,
  state: string,
): Promise<PreDeploymentReport> {
  // Get all historical reports for this city
  const { data: reports } = await supabase
    .from('reports')
    .select('latitude, longitude, address, category, size_rating, hazard_level, created_at')
    .eq('city', city)
    .eq('state', state)
    .order('created_at', { ascending: true });

  if (!reports || reports.length === 0) {
    return emptyReport(city, state);
  }

  // Grid clustering to find recurring locations
  const gridSize = 0.002; // ~200m cells
  const locationHistory: Map<string, {
    lat: number; lng: number; address?: string; category: string;
    months: Set<number>; years: Set<number>; count: number;
    sizes: string[]; hazards: string[];
  }> = new Map();

  for (const report of reports) {
    const key = `${Math.round(report.latitude / gridSize) * gridSize},${Math.round(report.longitude / gridSize) * gridSize},${report.category}`;
    const date = new Date(report.created_at);

    if (!locationHistory.has(key)) {
      locationHistory.set(key, {
        lat: report.latitude, lng: report.longitude, address: report.address,
        category: report.category,
        months: new Set(), years: new Set(), count: 0,
        sizes: [], hazards: [],
      });
    }

    const entry = locationHistory.get(key)!;
    entry.months.add(date.getMonth());
    entry.years.add(date.getFullYear());
    entry.count++;
    if (report.size_rating) entry.sizes.push(report.size_rating);
    if (report.hazard_level) entry.hazards.push(report.hazard_level);
  }

  // Filter to recurring issues (2+ years or 3+ reports)
  const predictions: SeasonalPrediction[] = [];
  const currentMonth = new Date().getMonth();

  for (const [_, entry] of locationHistory) {
    if (entry.years.size < 2 && entry.count < 3) continue;

    // Determine typical months
    const typicalMonths = Array.from(entry.months).sort().map((m) => MONTH_NAMES[m]);

    // Determine if upcoming season is relevant
    const monthsArray = Array.from(entry.months);
    const isUpcoming = monthsArray.some((m) => {
      const diff = ((m - currentMonth) + 12) % 12;
      return diff <= 3; // Within next 3 months
    });

    if (!isUpcoming && entry.count < 5) continue;

    // Estimate cost
    const mostCommonSize = mode(entry.sizes) || 'medium';
    const mostCommonHazard = mode(entry.hazards) || 'moderate';
    const cost = estimateRepairCost(entry.category as any, mostCommonSize as any, mostCommonHazard as any);

    predictions.push({
      location: { lat: entry.lat, lng: entry.lng, address: entry.address, city },
      category: entry.category,
      historicalReports: entry.count,
      yearsRecurring: entry.years.size,
      typicalMonths,
      estimatedRepairCost: cost.estimatedCostMid,
      confidence: Math.min(0.95, 0.4 + (entry.years.size * 0.15) + (entry.count * 0.05)),
      recommendation: entry.years.size >= 3
        ? 'High priority — recurring issue, recommend pre-emptive repair'
        : entry.count >= 5
          ? 'Moderate priority — frequent reports, monitor and prepare materials'
          : 'Watch list — emerging pattern',
    });
  }

  predictions.sort((a, b) => b.confidence - a.confidence);
  const topPredictions = predictions.slice(0, 30);

  const totalCost = topPredictions.reduce((sum, p) => sum + p.estimatedRepairCost, 0);
  // Proactive repair typically costs 40-60% less than reactive (FHWA data)
  const proactiveSavings = Math.round(totalCost * 0.5);

  const season = getSeason(currentMonth);

  const fullText = `
PRE-DEPLOYMENT MAINTENANCE REPORT
${city}, ${state} — ${season} Season
Generated by Fault Line Community Data
${'═'.repeat(60)}

Date: ${new Date().toLocaleDateString()}
Based on: ${reports.length} historical community reports

EXECUTIVE SUMMARY
${'─'.repeat(60)}
${topPredictions.length} locations identified as likely to need repair this ${season.toLowerCase()}.
Total estimated repair cost: $${totalCost.toLocaleString()}
Estimated savings via proactive deployment: $${proactiveSavings.toLocaleString()}

PREDICTED LOCATIONS
${'─'.repeat(60)}
${topPredictions.map((p, i) => `
${i + 1}. ${p.category.replace('_', ' ').toUpperCase()} — ${p.location.address || `${p.location.lat.toFixed(4)}, ${p.location.lng.toFixed(4)}`}
   Historical reports: ${p.historicalReports} over ${p.yearsRecurring} year(s)
   Typical months: ${p.typicalMonths.join(', ')}
   Estimated cost: $${p.estimatedRepairCost.toLocaleString()}
   Confidence: ${Math.round(p.confidence * 100)}%
   Recommendation: ${p.recommendation}
   Maps: https://maps.google.com/?q=${p.location.lat},${p.location.lng}
`).join('')}

METHODOLOGY
${'─'.repeat(60)}
Predictions are based on spatial clustering of ${reports.length} community-submitted reports,
analyzing recurring patterns by location, category, and season. Locations with multi-year
recurrence patterns receive the highest confidence ratings.

COST METHODOLOGY
${'─'.repeat(60)}
Repair cost estimates based on FHWA and ASCE averages adjusted for category, size, and severity.
Proactive repair savings estimate based on FHWA research showing 40-60% cost reduction
for preventive vs. reactive maintenance strategies.

${'═'.repeat(60)}
Generated by Fault Line — Community Infrastructure Accountability Platform
`.trim();

  return {
    title: `Pre-Deployment Report: ${city}, ${state} — ${season}`,
    city, state, season,
    generatedAt: new Date().toISOString(),
    predictions: topPredictions,
    totalEstimatedCost: totalCost,
    proactiveSavings,
    fullText,
  };
}

function emptyReport(city: string, state: string): PreDeploymentReport {
  return {
    title: `Pre-Deployment Report: ${city}, ${state}`,
    city, state, season: getSeason(new Date().getMonth()),
    generatedAt: new Date().toISOString(),
    predictions: [], totalEstimatedCost: 0, proactiveSavings: 0,
    fullText: 'Insufficient historical data to generate predictions.',
  };
}

function getSeason(month: number): string {
  if (month >= 2 && month <= 4) return 'Spring';
  if (month >= 5 && month <= 7) return 'Summer';
  if (month >= 8 && month <= 10) return 'Fall';
  return 'Winter';
}

function mode(arr: string[]): string | undefined {
  const counts: Record<string, number> = {};
  for (const v of arr) counts[v] = (counts[v] || 0) + 1;
  let maxCount = 0, maxVal: string | undefined;
  for (const [val, count] of Object.entries(counts)) {
    if (count > maxCount) { maxCount = count; maxVal = val; }
  }
  return maxVal;
}
